[book]
authors = ["reichtum"]
language = "en"
multilingual = false
src = "src"
title = "mdbook-template"

[output.html]
additional-css = ["custom.css"]

[preprocessor.wikilinks]

[preprocessor.katex]
